[package]
name = "xmemhash"
version = "1.0.0"
edition = "2021"
authors = ["Jake W. Ireland <jakewilliami@icloud.com>"]

[dependencies]
clap = { version = "4.5.20", features = ["cargo", "wrap_help", "derive"] }
infer = "0.16.0"
sha2 = "0.10.8"
tabular = "0.2.0"
zip = "2.2.0"
