[package]
name = "xmemhash"
version = "0.1.0"
edition = "2021"
authors = ["Jake W. Ireland <jakewilliami@icloud.com>"]

[dependencies]
clap = { version = "4.5.20", features = ["cargo", "wrap_help", "derive"] }
